name: pos_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  bloc: ^8.1.4
  cloud_firestore: ^4.14.0
  dartz: ^0.10.1
  dio: ^5.6.0
  equatable: ^2.0.5
  file_picker: ^8.1.2
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  foundation: ^0.0.5
  http: ^0.13.6
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.5
  localstorage: ^4.0.1+4
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
